### ISSUE TITLE
Question: Convert to Python datetime

### ISSUE THREAD

**Issue by g3rd** [neo4j-drivers/neotime#3]
Hello,

How do I convert the `neotime.DateTime` instance to a Python `datetime.datetime` instance?

But what I really need is the epoch seconds.

Right now I'm doing:

```python
import datetime
from neotime import DateTime

dt = DateTime(year=2018, month=9, day=26, hour=13, minute=31, second=5.0)
pdt = datetime.datetime(dt.year, dt.month, dt.day, dt.hour, dt.minute, int(dt.second))
timestamp = pdt.timestamp()
```

With this example, I'm losing milliseconds.

**Comment by technige** [comment]
You're almost there. To include the fractional seconds as microseconds, you'll need:
```
pdt = datetime.datetime(dt.year, dt.month, dt.day, dt.hour, dt.minute,
                        int(dt.second), int(dt.second * 1000000 % 1000000))
```

**Comment by technige** [comment]
Note also `ClockTime`, which might be useful for your use case:
```
>>> from neotime import DateTime
>>> dt = DateTime(year=2018, month=9, day=26, hour=13, minute=31, second=5.67)
>>> dt.to_clock_time()
ClockTime(seconds=63673565465, nanoseconds=670000000)
```

**Comment by technige** [comment]
Additional functions have now been added for coercion to native temporal types -> https://github.com/neo4j-drivers/neotime/commit/e32942f1ef794874d2f43673e50ee9b38e29ed53

**Comment by ShreyasJothish** [comment]
When working with Graphene and Neo4j, I ran into similar issue. Solved it using below code.

```
import datetime
import graphene
from neotime import DateTime

class CustomGrapheneDateTime(graphene.DateTime):
    @staticmethod
    def serialize(date):
        if isinstance(date, DateTime):
            date = datetime.datetime(date.year, date.month, date.day,
                                     date.hour, date.minute, int(date.second),
                                     int(date.second * 1000000 % 1000000),
                                     tzinfo=date.tzinfo)
        return graphene.DateTime.serialize(date)
```

**Comment by p1zz4br0etch3n** [comment]
> Additional functions have now been added for coercion to native temporal types -> [e32942f](https://github.com/neo4j-drivers/neotime/commit/e32942f1ef794874d2f43673e50ee9b38e29ed53)

Exactly what I was looking for. Would be nice to have that mentioned in the [documentation](https://neotime.readthedocs.io/en/latest/datetime.html#DateTime) though.
